name: Build

on:
  push:
    branches:
      - rebranding-2024
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          extended: true

      - name: Clean public directory
        run: rm -rf public

      - name: Build site
        run: hugo

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/rebranding-2024' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public

